labels:
  'fix':
    include:
      - '\bfix\b'
  'documentation':
    include:
      - '\bdocs\b'
  'test':
    include:
      - 'test'
  'feat':
    include:
      - 'feat'
  'bug':
    include:
      - 'bug'
  'refactor':
    include:
      - 'refactor'
  'chore':
    include:
      - 'chore'
